name: CI/CD Pipeline for To-Do App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Kubernetes config
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > ~/.kube/config

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t my-app:$GITHUB_SHA .
          docker push my-app:$GITHUB_SHA
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
