name: CI/CD Pipeline for To-Do App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          # Build Docker image using the Dockerfile in the root directory
          docker buildx build -f Dockerfile --platform linux/amd64,linux/arm64 -t my-app:$GITHUB_SHA .
        
      - name: Push Docker image
        run: |
          # Push the Docker image to the repository
          docker push my-app:$GITHUB_SHA

      - name: Set up Kubernetes (optional)
        run: |
          # Assuming you're using kubectl to deploy to a Kubernetes cluster
          # If you want to apply the Kubernetes deployment and service files from the 'k8s' folder
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/services.yml
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
