name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker (Install Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or another registry if needed)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build -f docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-list-app:latest

      # Optional: Add more steps to deploy the app or other tasks
